"use client"

import Link from "next/link"
import { useCallback, useEffect, useState } from "react"
import { Activity, CheckCircle2, Compass, FileWarning, MapPin, Phone, Shield, Siren, Sparkles, Users, Hospital, Navigation } from "lucide-react"
import { AuthService, type User } from "@/lib/auth"
import { useRouteUser } from "@/components/auth/demo-route"
import { EmergencyService, type EmergencyContact } from "@/lib/emergency"
import { LocationStatus } from "@/components/location/location-status"
import { InteractiveMap } from "@/components/location/interactive-map"
import { SOSButton } from "@/components/emergency/sos-button"
import { DigitalTouristId } from "@/components/tourist/digital-tourist-id"
import type { LocationData } from "@/lib/location"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"

export function TouristDashboard() {
  const routeUser = useRouteUser()
  const [legacyUser, setLegacyUser] = useState<User | null>(null)
  const [location, setLocation] = useState<LocationData | null>(null)

  useEffect(() => {
    if (!routeUser) setLegacyUser(AuthService.getCurrentUser())
  }, [routeUser])
  const onLocationDetected = useCallback((nextLocation: LocationData) => setLocation(nextLocation), [])
  const user = routeUser ?? legacyUser

  if (!user) return null

  const savedContacts = EmergencyService.getEmergencyContacts()
  const contacts: EmergencyContact[] = savedContacts.length > 0 ? savedContacts.slice(0, 3) : [
    { id: "demo-contact-1", name: "Maya Chen", phone: "+1 (212) 555-0148", relationship: "Sister", isPrimary: true },
    { id: "demo-contact-2", name: "Daniel Brooks", phone: "+1 (646) 555-0182", relationship: "Travel partner", isPrimary: false },
  ]
  const readableLocation = location?.address ?? "Location pending"
  const locationTime = location ? new Date(location.timestamp).toLocaleTimeString() : "Waiting for browser permission"

  return <div className="space-y-6 pb-8">
    <section className="rounded-2xl bg-slate-950 px-5 py-7 text-white shadow-lg sm:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Badge className="mb-4 border border-teal-300/30 bg-teal-300/15 text-teal-100 hover:bg-teal-300/15">DEMO MONITORING ACTIVE</Badge><h1 className="text-3xl font-bold sm:text-4xl">You&apos;re covered, {user.name.split(" ")[0]}.</h1><p className="mt-3 max-w-xl text-slate-300">SafeVoyage is keeping your trip in view and ready to help if something changes.</p></div><div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/10 px-4 py-3"><span className="h-3 w-3 rounded-full bg-emerald-400" /><div><p className="text-sm font-semibold">Online and watching</p><p className="text-xs text-slate-300">Demo safety monitor active</p></div></div></div></section>

    <section className="grid gap-6 lg:grid-cols-2"><Card className="border-emerald-200 bg-gradient-to-br from-emerald-50 to-white"><CardHeader className="flex flex-row items-start justify-between space-y-0"><div><CardDescription className="uppercase tracking-[0.16em] text-emerald-700">Demo-derived readiness</CardDescription><CardTitle className="mt-2 text-2xl">Safety score</CardTitle></div><Shield className="h-9 w-9 text-emerald-500" /></CardHeader><CardContent><p className="text-4xl font-bold">82<span className="text-lg text-muted-foreground"> / 100</span></p><p className="mt-1 text-sm text-emerald-700">Good preparation</p><Progress value={82} className="mt-5 h-2 bg-emerald-100" /><p className="mt-4 text-xs text-muted-foreground">Demo score based on contacts, location sharing, and the selected safety zone. It is not an AI risk prediction.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="h-5 w-5 text-emerald-600" /> Current Location</CardTitle><CardDescription>Real browser/device GPS reading</CardDescription></CardHeader><CardContent><LocationStatus onLocationDetected={onLocationDetected} /></CardContent></Card></section>

    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(300px,0.75fr)]"><Card className="overflow-hidden"><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle>Safety map</CardTitle><CardDescription>{location ? "Centered on your actual detected location" : "Waiting for location permission"}</CardDescription></div><Badge variant="outline">Demo map</Badge></CardHeader><CardContent className="p-0"><div className="h-[280px]">{location ? <InteractiveMap onLocationSelect={() => undefined} currentLocation={{ lat: location.latitude, lng: location.longitude }} safetyZone="green" /> : <div className="flex h-full items-center justify-center p-6 text-center text-sm text-muted-foreground">Allow browser location access to display your position.</div>}</div></CardContent></Card><Card><CardHeader><CardTitle>Recent safety activity</CardTitle><CardDescription>Activity from this browser session</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-50 text-blue-600"><MapPin className="h-4 w-4" /></span><div><p className="text-sm font-semibold">Location updated</p><p className="text-xs text-muted-foreground">{readableLocation}</p><p className="text-xs text-muted-foreground">{locationTime}</p></div></div><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-sm font-semibold">Safety check completed</p><p className="text-xs text-muted-foreground">Demo readiness status refreshed</p></div></div><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-violet-50 text-violet-600"><Activity className="h-4 w-4" /></span><div><p className="text-sm font-semibold">Monitoring ready</p><p className="text-xs text-muted-foreground">No background tracking is running</p></div></div></CardContent></Card></section>

    <section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" /> Emergency contacts</CardTitle><CardDescription>Demo contacts ready for your workflow</CardDescription></div><Link href="/contacts" className="text-sm font-semibold text-primary">Manage</Link></CardHeader><CardContent className="space-y-3">{contacts.map((contact) => <div key={contact.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="text-sm font-semibold">{contact.name}</p><p className="text-xs text-muted-foreground">{contact.relationship} · {contact.phone}</p></div><Badge variant="outline" className="border-emerald-200 text-emerald-700">Verified</Badge></div>)}</CardContent></Card><DigitalTouristId user={user} compact /></section>

    <section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Safety &amp; Contacts</CardTitle><CardDescription>Helpful demo resources for your current trip</CardDescription></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div><h3 className="mb-3 flex items-center gap-2 font-semibold"><Hospital className="h-4 w-4 text-primary" /> Nearby Safety Places</h3>{location ? <div className="space-y-3">{[{ icon: Hospital, name: "Nearest Hospital", detail: "Approx. 1.8 km · Sample nearby listing" }, { icon: Navigation, name: "Nearby Police Station", detail: "Approx. 2.4 km · Sample nearby listing" }, { icon: Shield, name: "Tourist Help / Information Center", detail: "Approx. 1.2 km · Sample nearby listing" }].map((place) => { const Icon = place.icon; return <div key={place.name} className="flex items-start gap-2 rounded-lg border p-3"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{place.name}</p><p className="text-xs text-muted-foreground">{place.detail}</p><div className="mt-2 flex gap-2"><Button asChild size="sm" variant="outline"><a href={`https://www.google.com/maps/dir/?api=1&destination=${location.latitude},${location.longitude}`} target="_blank" rel="noreferrer">Directions</a></Button>{place.name !== "Tourist Help / Information Center" && <Button asChild size="sm" variant="ghost"><a href="tel:112">Call</a></Button>}</div></div></div> })}</div> : <p className="rounded-lg border border-dashed p-3 text-sm text-muted-foreground">Enable location to see nearby safety places.</p>}</div><div><h3 className="mb-3 flex items-center gap-2 font-semibold"><Phone className="h-4 w-4 text-primary" /> Important Contacts</h3><div className="space-y-2"><div className="flex items-center justify-between rounded-lg border p-3"><span className="text-sm">Emergency</span><a href="tel:112" className="font-semibold text-primary">112</a></div><div className="flex items-center justify-between rounded-lg border p-3"><span className="text-sm">Tourist Helpline</span><a href="tel:1363" className="font-semibold text-primary">1363</a></div></div><p className="mb-2 mt-5 text-sm font-semibold">Emergency Contacts</p><div className="space-y-2">{contacts.length > 0 ? contacts.slice(0, 2).map((contact) => <div key={contact.id} className="rounded-lg bg-muted/50 px-3 py-2 text-xs"><span className="font-medium">{contact.name}</span><span className="text-muted-foreground"> · {contact.phone}</span></div>) : <p className="text-xs text-muted-foreground">No emergency contacts added yet.</p>}</div><Button asChild variant="outline" size="sm" className="mt-3"><Link href="/contacts">Manage Contacts</Link></Button></div></CardContent></Card></section>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Button asChild><Link href="/tourist/incidents"><FileWarning className="mr-2 h-4 w-4" /> Report Incident</Link></Button><Button asChild variant="destructive"><Link href="/emergency"><Siren className="mr-2 h-4 w-4" /> Emergency SOS</Link></Button><Button asChild variant="outline"><Link href="/location"><Compass className="mr-2 h-4 w-4" /> Safety Map</Link></Button><Button asChild variant="outline"><Link href="/assistant"><Sparkles className="mr-2 h-4 w-4" /> Safety Assistant</Link></Button></section>
    <Card className="border-rose-200 bg-rose-50/70"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-rose-950">Need immediate help?</p><p className="text-sm text-rose-800">Creates a local demo alert for the SafeVoyage authority dashboard. It does not contact emergency services.</p></div><SOSButton userId={user.id} touristName={user.name} /></CardContent></Card>
  </div>
}
