"use client"

import { useEffect, useState } from "react"
import { AlertTriangle, Clock, MapPin, Shield, Users } from "lucide-react"
import { DemoResponseService, DEMO_RESPONDERS, type DemoSosAlert } from "@/lib/demo-response"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function AuthorityWorkspace() {
  const [incidents, setIncidents] = useState<Array<{ id: string; title: string; severity: string; status: string; location: string | null; createdAt: string; tourist: { name: string } }>>([])
  const [alerts, setAlerts] = useState<DemoSosAlert[]>([])
  useEffect(() => { const load = async () => { const response = await fetch("/api/incidents", { cache: "no-store" }); if (response.ok) setIncidents((await response.json()).incidents) }; const refresh = () => setAlerts(DemoResponseService.getSosAlerts()); void load(); refresh(); window.addEventListener("storage", refresh); return () => window.removeEventListener("storage", refresh) }, [])
  const openIncidents = incidents.filter((incident) => incident.status !== "RESOLVED")
  const activeAlerts = alerts.filter((alert) => alert.status !== "RESOLVED")
  const metrics = [{ label: "Active Incidents", value: openIncidents.length, icon: AlertTriangle }, { label: "Active SOS", value: activeAlerts.length, icon: Shield }, { label: "Open Reports", value: openIncidents.length, icon: Clock }, { label: "Responders", value: DEMO_RESPONDERS.length, icon: Users }]
  return <div className="space-y-6"><div><Badge variant="secondary" className="mb-2">OPERATIONAL DEMO</Badge><h1 className="text-3xl font-bold">Authority Command Center</h1><p className="text-muted-foreground">Database incidents and shared demo emergency alerts in one view.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-center gap-3 p-5"><Icon className="h-6 w-6 text-primary" /><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Recent Incidents</CardTitle><CardDescription>Loaded from PostgreSQL</CardDescription></CardHeader><CardContent className="space-y-3">{incidents.slice(0, 5).map((incident) => <div key={incident.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{incident.title}</span><Badge variant="outline">{incident.status}</Badge><Badge variant="secondary">{incident.severity}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{incident.tourist.name} · {incident.location ?? "Location unavailable"}</p></div>)}{incidents.length === 0 && <p className="text-sm text-muted-foreground">No active incidents</p>}</CardContent></Card><Card><CardHeader><CardTitle>Active Emergency Alerts</CardTitle><CardDescription>Shared demo SOS alerts; no external notifications are sent.</CardDescription></CardHeader><CardContent className="space-y-3">{activeAlerts.map((alert) => <div key={alert.id} className="rounded-lg border border-rose-200 bg-rose-50 p-3"><p className="font-semibold text-rose-900">{alert.touristName} · {alert.status}</p><p className="flex items-center gap-1 text-sm text-rose-800"><MapPin className="h-4 w-4" />{alert.location.address ?? "Location unavailable"}</p></div>)}{activeAlerts.length === 0 && <p className="text-sm text-muted-foreground">No active SOS alerts</p>}</CardContent></Card></div>
}
